version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "windows-10"
  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false

    post_install:
      - poetry install --only doc